//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin.Models.EntytyLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonProdu
    {
        public int bon { get; set; }
        public int produs { get; set; }
        public int cantitate { get; set; }
        public decimal subtotal { get; set; }
        public bool active { get; set; }
    
        public virtual Bonuri Bonuri { get; set; }
        public virtual Produse Produse { get; set; }
    }
}
