//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MagazinModel", "FK_BonProdus_Bon", "Bonuri", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Magazin.Models.EntytyLayer.Bonuri), "BonProdus", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Magazin.Models.EntytyLayer.BonProdu), true)]
[assembly: EdmRelationshipAttribute("MagazinModel", "FK_BonProdus_Produs", "Produse", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Magazin.Models.EntytyLayer.Produse), "BonProdus", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Magazin.Models.EntytyLayer.BonProdu), true)]
[assembly: EdmRelationshipAttribute("MagazinModel", "FK_Bon_Operator", "Utilizatori", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Magazin.Models.EntytyLayer.Utilizatori), "Bonuri", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Magazin.Models.EntytyLayer.Bonuri), true)]
[assembly: EdmRelationshipAttribute("MagazinModel", "FK_Produse_Categorii", "Categorii", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Magazin.Models.EntytyLayer.Categorii), "Produse", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Magazin.Models.EntytyLayer.Produse), true)]
[assembly: EdmRelationshipAttribute("MagazinModel", "FK_Produse_Producatori", "Producatori", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Magazin.Models.EntytyLayer.Producatori), "Produse", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Magazin.Models.EntytyLayer.Produse), true)]
[assembly: EdmRelationshipAttribute("MagazinModel", "FK_Stocuri_Produse", "Produse", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Magazin.Models.EntytyLayer.Produse), "Stocuri", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Magazin.Models.EntytyLayer.Stocuri), true)]

#endregion

namespace Magazin.Models.EntytyLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MagazinEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MagazinEntities object using the connection string found in the 'MagazinEntities' section of the application configuration file.
        /// </summary>
        public MagazinEntities() : base("name=MagazinEntities", "MagazinEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MagazinEntities object.
        /// </summary>
        public MagazinEntities(string connectionString) : base(connectionString, "MagazinEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MagazinEntities object.
        /// </summary>
        public MagazinEntities(EntityConnection connection) : base(connection, "MagazinEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BonProdu> BonProdus
        {
            get
            {
                if ((_BonProdus == null))
                {
                    _BonProdus = base.CreateObjectSet<BonProdu>("BonProdus");
                }
                return _BonProdus;
            }
        }
        private ObjectSet<BonProdu> _BonProdus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bonuri> Bonuris
        {
            get
            {
                if ((_Bonuris == null))
                {
                    _Bonuris = base.CreateObjectSet<Bonuri>("Bonuris");
                }
                return _Bonuris;
            }
        }
        private ObjectSet<Bonuri> _Bonuris;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Categorii> Categoriis
        {
            get
            {
                if ((_Categoriis == null))
                {
                    _Categoriis = base.CreateObjectSet<Categorii>("Categoriis");
                }
                return _Categoriis;
            }
        }
        private ObjectSet<Categorii> _Categoriis;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Producatori> Producatoris
        {
            get
            {
                if ((_Producatoris == null))
                {
                    _Producatoris = base.CreateObjectSet<Producatori>("Producatoris");
                }
                return _Producatoris;
            }
        }
        private ObjectSet<Producatori> _Producatoris;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Produse> Produses
        {
            get
            {
                if ((_Produses == null))
                {
                    _Produses = base.CreateObjectSet<Produse>("Produses");
                }
                return _Produses;
            }
        }
        private ObjectSet<Produse> _Produses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Stocuri> Stocuris
        {
            get
            {
                if ((_Stocuris == null))
                {
                    _Stocuris = base.CreateObjectSet<Stocuri>("Stocuris");
                }
                return _Stocuris;
            }
        }
        private ObjectSet<Stocuri> _Stocuris;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Utilizatori> Utilizatoris
        {
            get
            {
                if ((_Utilizatoris == null))
                {
                    _Utilizatoris = base.CreateObjectSet<Utilizatori>("Utilizatoris");
                }
                return _Utilizatoris;
            }
        }
        private ObjectSet<Utilizatori> _Utilizatoris;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BonProdus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBonProdus(BonProdu bonProdu)
        {
            base.AddObject("BonProdus", bonProdu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bonuris EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBonuris(Bonuri bonuri)
        {
            base.AddObject("Bonuris", bonuri);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categoriis EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategoriis(Categorii categorii)
        {
            base.AddObject("Categoriis", categorii);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Producatoris EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducatoris(Producatori producatori)
        {
            base.AddObject("Producatoris", producatori);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Produses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProduses(Produse produse)
        {
            base.AddObject("Produses", produse);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Stocuris EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStocuris(Stocuri stocuri)
        {
            base.AddObject("Stocuris", stocuri);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Utilizatoris EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUtilizatoris(Utilizatori utilizatori)
        {
            base.AddObject("Utilizatoris", utilizatori);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MagazinModel", Name="BonProdu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BonProdu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BonProdu object.
        /// </summary>
        /// <param name="bon">Initial value of the bon property.</param>
        /// <param name="produs">Initial value of the produs property.</param>
        /// <param name="cantitate">Initial value of the cantitate property.</param>
        /// <param name="subtotal">Initial value of the subtotal property.</param>
        public static BonProdu CreateBonProdu(global::System.Int32 bon, global::System.Int32 produs, global::System.Int32 cantitate, global::System.Decimal subtotal)
        {
            BonProdu bonProdu = new BonProdu();
            bonProdu.bon = bon;
            bonProdu.produs = produs;
            bonProdu.cantitate = cantitate;
            bonProdu.subtotal = subtotal;
            return bonProdu;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bon
        {
            get
            {
                return _bon;
            }
            set
            {
                if (_bon != value)
                {
                    OnbonChanging(value);
                    ReportPropertyChanging("bon");
                    _bon = StructuralObject.SetValidValue(value, "bon");
                    ReportPropertyChanged("bon");
                    OnbonChanged();
                }
            }
        }
        private global::System.Int32 _bon;
        partial void OnbonChanging(global::System.Int32 value);
        partial void OnbonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 produs
        {
            get
            {
                return _produs;
            }
            set
            {
                if (_produs != value)
                {
                    OnprodusChanging(value);
                    ReportPropertyChanging("produs");
                    _produs = StructuralObject.SetValidValue(value, "produs");
                    ReportPropertyChanged("produs");
                    OnprodusChanged();
                }
            }
        }
        private global::System.Int32 _produs;
        partial void OnprodusChanging(global::System.Int32 value);
        partial void OnprodusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cantitate
        {
            get
            {
                return _cantitate;
            }
            set
            {
                OncantitateChanging(value);
                ReportPropertyChanging("cantitate");
                _cantitate = StructuralObject.SetValidValue(value, "cantitate");
                ReportPropertyChanged("cantitate");
                OncantitateChanged();
            }
        }
        private global::System.Int32 _cantitate;
        partial void OncantitateChanging(global::System.Int32 value);
        partial void OncantitateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal subtotal
        {
            get
            {
                return _subtotal;
            }
            set
            {
                OnsubtotalChanging(value);
                ReportPropertyChanging("subtotal");
                _subtotal = StructuralObject.SetValidValue(value, "subtotal");
                ReportPropertyChanged("subtotal");
                OnsubtotalChanged();
            }
        }
        private global::System.Decimal _subtotal;
        partial void OnsubtotalChanging(global::System.Decimal value);
        partial void OnsubtotalChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MagazinModel", "FK_BonProdus_Bon", "Bonuri")]
        public Bonuri Bonuri
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bonuri>("MagazinModel.FK_BonProdus_Bon", "Bonuri").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bonuri>("MagazinModel.FK_BonProdus_Bon", "Bonuri").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bonuri> BonuriReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bonuri>("MagazinModel.FK_BonProdus_Bon", "Bonuri");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bonuri>("MagazinModel.FK_BonProdus_Bon", "Bonuri", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MagazinModel", "FK_BonProdus_Produs", "Produse")]
        public Produse Produse
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produse>("MagazinModel.FK_BonProdus_Produs", "Produse").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produse>("MagazinModel.FK_BonProdus_Produs", "Produse").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Produse> ProduseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produse>("MagazinModel.FK_BonProdus_Produs", "Produse");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Produse>("MagazinModel.FK_BonProdus_Produs", "Produse", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MagazinModel", Name="Bonuri")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bonuri : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bonuri object.
        /// </summary>
        /// <param name="iDbon">Initial value of the IDbon property.</param>
        /// <param name="emitere">Initial value of the emitere property.</param>
        /// <param name="operator">Initial value of the operator property.</param>
        public static Bonuri CreateBonuri(global::System.Int32 iDbon, global::System.DateTime emitere, global::System.Int32 @operator)
        {
            Bonuri bonuri = new Bonuri();
            bonuri.IDbon = iDbon;
            bonuri.emitere = emitere;
            bonuri.@operator = @operator;
            return bonuri;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDbon
        {
            get
            {
                return _IDbon;
            }
            set
            {
                if (_IDbon != value)
                {
                    OnIDbonChanging(value);
                    ReportPropertyChanging("IDbon");
                    _IDbon = StructuralObject.SetValidValue(value, "IDbon");
                    ReportPropertyChanged("IDbon");
                    OnIDbonChanged();
                }
            }
        }
        private global::System.Int32 _IDbon;
        partial void OnIDbonChanging(global::System.Int32 value);
        partial void OnIDbonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime emitere
        {
            get
            {
                return _emitere;
            }
            set
            {
                OnemitereChanging(value);
                ReportPropertyChanging("emitere");
                _emitere = StructuralObject.SetValidValue(value, "emitere");
                ReportPropertyChanged("emitere");
                OnemitereChanged();
            }
        }
        private global::System.DateTime _emitere;
        partial void OnemitereChanging(global::System.DateTime value);
        partial void OnemitereChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 @operator
        {
            get
            {
                return _operator;
            }
            set
            {
                OnoperatorChanging(value);
                ReportPropertyChanging("operator");
                _operator = StructuralObject.SetValidValue(value, "operator");
                ReportPropertyChanged("operator");
                OnoperatorChanged();
            }
        }
        private global::System.Int32 _operator;
        partial void OnoperatorChanging(global::System.Int32 value);
        partial void OnoperatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> total
        {
            get
            {
                return _total;
            }
            set
            {
                OntotalChanging(value);
                ReportPropertyChanging("total");
                _total = StructuralObject.SetValidValue(value, "total");
                ReportPropertyChanged("total");
                OntotalChanged();
            }
        }
        private Nullable<global::System.Decimal> _total;
        partial void OntotalChanging(Nullable<global::System.Decimal> value);
        partial void OntotalChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MagazinModel", "FK_BonProdus_Bon", "BonProdus")]
        public EntityCollection<BonProdu> BonProdus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BonProdu>("MagazinModel.FK_BonProdus_Bon", "BonProdus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BonProdu>("MagazinModel.FK_BonProdus_Bon", "BonProdus", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MagazinModel", "FK_Bon_Operator", "Utilizatori")]
        public Utilizatori Utilizatori
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilizatori>("MagazinModel.FK_Bon_Operator", "Utilizatori").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilizatori>("MagazinModel.FK_Bon_Operator", "Utilizatori").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Utilizatori> UtilizatoriReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Utilizatori>("MagazinModel.FK_Bon_Operator", "Utilizatori");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Utilizatori>("MagazinModel.FK_Bon_Operator", "Utilizatori", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MagazinModel", Name="Categorii")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Categorii : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Categorii object.
        /// </summary>
        /// <param name="iDcategorie">Initial value of the IDcategorie property.</param>
        /// <param name="categorie">Initial value of the categorie property.</param>
        public static Categorii CreateCategorii(global::System.Int32 iDcategorie, global::System.String categorie)
        {
            Categorii categorii = new Categorii();
            categorii.IDcategorie = iDcategorie;
            categorii.categorie = categorie;
            return categorii;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDcategorie
        {
            get
            {
                return _IDcategorie;
            }
            set
            {
                if (_IDcategorie != value)
                {
                    OnIDcategorieChanging(value);
                    ReportPropertyChanging("IDcategorie");
                    _IDcategorie = StructuralObject.SetValidValue(value, "IDcategorie");
                    ReportPropertyChanged("IDcategorie");
                    OnIDcategorieChanged();
                }
            }
        }
        private global::System.Int32 _IDcategorie;
        partial void OnIDcategorieChanging(global::System.Int32 value);
        partial void OnIDcategorieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String categorie
        {
            get
            {
                return _categorie;
            }
            set
            {
                OncategorieChanging(value);
                ReportPropertyChanging("categorie");
                _categorie = StructuralObject.SetValidValue(value, false, "categorie");
                ReportPropertyChanged("categorie");
                OncategorieChanged();
            }
        }
        private global::System.String _categorie;
        partial void OncategorieChanging(global::System.String value);
        partial void OncategorieChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MagazinModel", "FK_Produse_Categorii", "Produse")]
        public EntityCollection<Produse> Produses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Produse>("MagazinModel.FK_Produse_Categorii", "Produse");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Produse>("MagazinModel.FK_Produse_Categorii", "Produse", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MagazinModel", Name="Producatori")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Producatori : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Producatori object.
        /// </summary>
        /// <param name="iDproducator">Initial value of the IDproducator property.</param>
        /// <param name="nume_producator">Initial value of the nume_producator property.</param>
        /// <param name="tara_origine">Initial value of the tara_origine property.</param>
        public static Producatori CreateProducatori(global::System.Int32 iDproducator, global::System.String nume_producator, global::System.String tara_origine)
        {
            Producatori producatori = new Producatori();
            producatori.IDproducator = iDproducator;
            producatori.nume_producator = nume_producator;
            producatori.tara_origine = tara_origine;
            return producatori;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDproducator
        {
            get
            {
                return _IDproducator;
            }
            set
            {
                if (_IDproducator != value)
                {
                    OnIDproducatorChanging(value);
                    ReportPropertyChanging("IDproducator");
                    _IDproducator = StructuralObject.SetValidValue(value, "IDproducator");
                    ReportPropertyChanged("IDproducator");
                    OnIDproducatorChanged();
                }
            }
        }
        private global::System.Int32 _IDproducator;
        partial void OnIDproducatorChanging(global::System.Int32 value);
        partial void OnIDproducatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nume_producator
        {
            get
            {
                return _nume_producator;
            }
            set
            {
                Onnume_producatorChanging(value);
                ReportPropertyChanging("nume_producator");
                _nume_producator = StructuralObject.SetValidValue(value, false, "nume_producator");
                ReportPropertyChanged("nume_producator");
                Onnume_producatorChanged();
            }
        }
        private global::System.String _nume_producator;
        partial void Onnume_producatorChanging(global::System.String value);
        partial void Onnume_producatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tara_origine
        {
            get
            {
                return _tara_origine;
            }
            set
            {
                Ontara_origineChanging(value);
                ReportPropertyChanging("tara_origine");
                _tara_origine = StructuralObject.SetValidValue(value, false, "tara_origine");
                ReportPropertyChanged("tara_origine");
                Ontara_origineChanged();
            }
        }
        private global::System.String _tara_origine;
        partial void Ontara_origineChanging(global::System.String value);
        partial void Ontara_origineChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MagazinModel", "FK_Produse_Producatori", "Produse")]
        public EntityCollection<Produse> Produses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Produse>("MagazinModel.FK_Produse_Producatori", "Produse");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Produse>("MagazinModel.FK_Produse_Producatori", "Produse", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MagazinModel", Name="Produse")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Produse : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Produse object.
        /// </summary>
        /// <param name="iDprodus">Initial value of the IDprodus property.</param>
        /// <param name="nume_prod">Initial value of the nume_prod property.</param>
        /// <param name="cod_bare">Initial value of the cod_bare property.</param>
        /// <param name="producator">Initial value of the producator property.</param>
        /// <param name="categorie">Initial value of the categorie property.</param>
        /// <param name="active">Initial value of the active property.</param>
        public static Produse CreateProduse(global::System.Int32 iDprodus, global::System.String nume_prod, global::System.String cod_bare, global::System.Int32 producator, global::System.Int32 categorie, global::System.Boolean active)
        {
            Produse produse = new Produse();
            produse.IDprodus = iDprodus;
            produse.nume_prod = nume_prod;
            produse.cod_bare = cod_bare;
            produse.producator = producator;
            produse.categorie = categorie;
            produse.active = active;
            return produse;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDprodus
        {
            get
            {
                return _IDprodus;
            }
            set
            {
                if (_IDprodus != value)
                {
                    OnIDprodusChanging(value);
                    ReportPropertyChanging("IDprodus");
                    _IDprodus = StructuralObject.SetValidValue(value, "IDprodus");
                    ReportPropertyChanged("IDprodus");
                    OnIDprodusChanged();
                }
            }
        }
        private global::System.Int32 _IDprodus;
        partial void OnIDprodusChanging(global::System.Int32 value);
        partial void OnIDprodusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nume_prod
        {
            get
            {
                return _nume_prod;
            }
            set
            {
                Onnume_prodChanging(value);
                ReportPropertyChanging("nume_prod");
                _nume_prod = StructuralObject.SetValidValue(value, false, "nume_prod");
                ReportPropertyChanged("nume_prod");
                Onnume_prodChanged();
            }
        }
        private global::System.String _nume_prod;
        partial void Onnume_prodChanging(global::System.String value);
        partial void Onnume_prodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cod_bare
        {
            get
            {
                return _cod_bare;
            }
            set
            {
                Oncod_bareChanging(value);
                ReportPropertyChanging("cod_bare");
                _cod_bare = StructuralObject.SetValidValue(value, false, "cod_bare");
                ReportPropertyChanged("cod_bare");
                Oncod_bareChanged();
            }
        }
        private global::System.String _cod_bare;
        partial void Oncod_bareChanging(global::System.String value);
        partial void Oncod_bareChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 producator
        {
            get
            {
                return _producator;
            }
            set
            {
                OnproducatorChanging(value);
                ReportPropertyChanging("producator");
                _producator = StructuralObject.SetValidValue(value, "producator");
                ReportPropertyChanged("producator");
                OnproducatorChanged();
            }
        }
        private global::System.Int32 _producator;
        partial void OnproducatorChanging(global::System.Int32 value);
        partial void OnproducatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 categorie
        {
            get
            {
                return _categorie;
            }
            set
            {
                OncategorieChanging(value);
                ReportPropertyChanging("categorie");
                _categorie = StructuralObject.SetValidValue(value, "categorie");
                ReportPropertyChanged("categorie");
                OncategorieChanged();
            }
        }
        private global::System.Int32 _categorie;
        partial void OncategorieChanging(global::System.Int32 value);
        partial void OncategorieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean active
        {
            get
            {
                return _active;
            }
            set
            {
                OnactiveChanging(value);
                ReportPropertyChanging("active");
                _active = StructuralObject.SetValidValue(value, "active");
                ReportPropertyChanged("active");
                OnactiveChanged();
            }
        }
        private global::System.Boolean _active;
        partial void OnactiveChanging(global::System.Boolean value);
        partial void OnactiveChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MagazinModel", "FK_BonProdus_Produs", "BonProdus")]
        public EntityCollection<BonProdu> BonProdus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BonProdu>("MagazinModel.FK_BonProdus_Produs", "BonProdus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BonProdu>("MagazinModel.FK_BonProdus_Produs", "BonProdus", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MagazinModel", "FK_Produse_Categorii", "Categorii")]
        public Categorii Categorii
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categorii>("MagazinModel.FK_Produse_Categorii", "Categorii").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categorii>("MagazinModel.FK_Produse_Categorii", "Categorii").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Categorii> CategoriiReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categorii>("MagazinModel.FK_Produse_Categorii", "Categorii");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Categorii>("MagazinModel.FK_Produse_Categorii", "Categorii", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MagazinModel", "FK_Produse_Producatori", "Producatori")]
        public Producatori Producatori
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producatori>("MagazinModel.FK_Produse_Producatori", "Producatori").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producatori>("MagazinModel.FK_Produse_Producatori", "Producatori").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Producatori> ProducatoriReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producatori>("MagazinModel.FK_Produse_Producatori", "Producatori");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Producatori>("MagazinModel.FK_Produse_Producatori", "Producatori", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MagazinModel", "FK_Stocuri_Produse", "Stocuri")]
        public EntityCollection<Stocuri> Stocuris
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Stocuri>("MagazinModel.FK_Stocuri_Produse", "Stocuri");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Stocuri>("MagazinModel.FK_Stocuri_Produse", "Stocuri", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MagazinModel", Name="Stocuri")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Stocuri : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Stocuri object.
        /// </summary>
        /// <param name="iDstoc">Initial value of the IDstoc property.</param>
        /// <param name="produs">Initial value of the produs property.</param>
        /// <param name="cantitate">Initial value of the cantitate property.</param>
        /// <param name="um">Initial value of the um property.</param>
        /// <param name="aprovizionare">Initial value of the aprovizionare property.</param>
        /// <param name="pret_achizitie">Initial value of the pret_achizitie property.</param>
        /// <param name="pret_vanzare">Initial value of the pret_vanzare property.</param>
        /// <param name="active">Initial value of the active property.</param>
        public static Stocuri CreateStocuri(global::System.Int32 iDstoc, global::System.Int32 produs, global::System.Int32 cantitate, global::System.String um, global::System.DateTime aprovizionare, global::System.Decimal pret_achizitie, global::System.Decimal pret_vanzare, global::System.Boolean active)
        {
            Stocuri stocuri = new Stocuri();
            stocuri.IDstoc = iDstoc;
            stocuri.produs = produs;
            stocuri.cantitate = cantitate;
            stocuri.um = um;
            stocuri.aprovizionare = aprovizionare;
            stocuri.pret_achizitie = pret_achizitie;
            stocuri.pret_vanzare = pret_vanzare;
            stocuri.active = active;
            return stocuri;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDstoc
        {
            get
            {
                return _IDstoc;
            }
            set
            {
                if (_IDstoc != value)
                {
                    OnIDstocChanging(value);
                    ReportPropertyChanging("IDstoc");
                    _IDstoc = StructuralObject.SetValidValue(value, "IDstoc");
                    ReportPropertyChanged("IDstoc");
                    OnIDstocChanged();
                }
            }
        }
        private global::System.Int32 _IDstoc;
        partial void OnIDstocChanging(global::System.Int32 value);
        partial void OnIDstocChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 produs
        {
            get
            {
                return _produs;
            }
            set
            {
                OnprodusChanging(value);
                ReportPropertyChanging("produs");
                _produs = StructuralObject.SetValidValue(value, "produs");
                ReportPropertyChanged("produs");
                OnprodusChanged();
            }
        }
        private global::System.Int32 _produs;
        partial void OnprodusChanging(global::System.Int32 value);
        partial void OnprodusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cantitate
        {
            get
            {
                return _cantitate;
            }
            set
            {
                OncantitateChanging(value);
                ReportPropertyChanging("cantitate");
                _cantitate = StructuralObject.SetValidValue(value, "cantitate");
                ReportPropertyChanged("cantitate");
                OncantitateChanged();
            }
        }
        private global::System.Int32 _cantitate;
        partial void OncantitateChanging(global::System.Int32 value);
        partial void OncantitateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String um
        {
            get
            {
                return _um;
            }
            set
            {
                OnumChanging(value);
                ReportPropertyChanging("um");
                _um = StructuralObject.SetValidValue(value, false, "um");
                ReportPropertyChanged("um");
                OnumChanged();
            }
        }
        private global::System.String _um;
        partial void OnumChanging(global::System.String value);
        partial void OnumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime aprovizionare
        {
            get
            {
                return _aprovizionare;
            }
            set
            {
                OnaprovizionareChanging(value);
                ReportPropertyChanging("aprovizionare");
                _aprovizionare = StructuralObject.SetValidValue(value, "aprovizionare");
                ReportPropertyChanged("aprovizionare");
                OnaprovizionareChanged();
            }
        }
        private global::System.DateTime _aprovizionare;
        partial void OnaprovizionareChanging(global::System.DateTime value);
        partial void OnaprovizionareChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> expirare
        {
            get
            {
                return _expirare;
            }
            set
            {
                OnexpirareChanging(value);
                ReportPropertyChanging("expirare");
                _expirare = StructuralObject.SetValidValue(value, "expirare");
                ReportPropertyChanged("expirare");
                OnexpirareChanged();
            }
        }
        private Nullable<global::System.DateTime> _expirare;
        partial void OnexpirareChanging(Nullable<global::System.DateTime> value);
        partial void OnexpirareChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal pret_achizitie
        {
            get
            {
                return _pret_achizitie;
            }
            set
            {
                Onpret_achizitieChanging(value);
                ReportPropertyChanging("pret_achizitie");
                _pret_achizitie = StructuralObject.SetValidValue(value, "pret_achizitie");
                ReportPropertyChanged("pret_achizitie");
                Onpret_achizitieChanged();
            }
        }
        private global::System.Decimal _pret_achizitie;
        partial void Onpret_achizitieChanging(global::System.Decimal value);
        partial void Onpret_achizitieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal pret_vanzare
        {
            get
            {
                return _pret_vanzare;
            }
            set
            {
                Onpret_vanzareChanging(value);
                ReportPropertyChanging("pret_vanzare");
                _pret_vanzare = StructuralObject.SetValidValue(value, "pret_vanzare");
                ReportPropertyChanged("pret_vanzare");
                Onpret_vanzareChanged();
            }
        }
        private global::System.Decimal _pret_vanzare;
        partial void Onpret_vanzareChanging(global::System.Decimal value);
        partial void Onpret_vanzareChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean active
        {
            get
            {
                return _active;
            }
            set
            {
                OnactiveChanging(value);
                ReportPropertyChanging("active");
                _active = StructuralObject.SetValidValue(value, "active");
                ReportPropertyChanged("active");
                OnactiveChanged();
            }
        }
        private global::System.Boolean _active;
        partial void OnactiveChanging(global::System.Boolean value);
        partial void OnactiveChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MagazinModel", "FK_Stocuri_Produse", "Produse")]
        public Produse Produse
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produse>("MagazinModel.FK_Stocuri_Produse", "Produse").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produse>("MagazinModel.FK_Stocuri_Produse", "Produse").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Produse> ProduseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produse>("MagazinModel.FK_Stocuri_Produse", "Produse");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Produse>("MagazinModel.FK_Stocuri_Produse", "Produse", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MagazinModel", Name="Utilizatori")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Utilizatori : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Utilizatori object.
        /// </summary>
        /// <param name="iDutilizator">Initial value of the IDutilizator property.</param>
        /// <param name="nume">Initial value of the nume property.</param>
        /// <param name="parola">Initial value of the parola property.</param>
        /// <param name="tip_utilizator">Initial value of the tip_utilizator property.</param>
        /// <param name="active">Initial value of the active property.</param>
        public static Utilizatori CreateUtilizatori(global::System.Int32 iDutilizator, global::System.String nume, global::System.String parola, global::System.Boolean tip_utilizator, global::System.Boolean active)
        {
            Utilizatori utilizatori = new Utilizatori();
            utilizatori.IDutilizator = iDutilizator;
            utilizatori.nume = nume;
            utilizatori.parola = parola;
            utilizatori.tip_utilizator = tip_utilizator;
            utilizatori.active = active;
            return utilizatori;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDutilizator
        {
            get
            {
                return _IDutilizator;
            }
            set
            {
                if (_IDutilizator != value)
                {
                    OnIDutilizatorChanging(value);
                    ReportPropertyChanging("IDutilizator");
                    _IDutilizator = StructuralObject.SetValidValue(value, "IDutilizator");
                    ReportPropertyChanged("IDutilizator");
                    OnIDutilizatorChanged();
                }
            }
        }
        private global::System.Int32 _IDutilizator;
        partial void OnIDutilizatorChanging(global::System.Int32 value);
        partial void OnIDutilizatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nume
        {
            get
            {
                return _nume;
            }
            set
            {
                OnnumeChanging(value);
                ReportPropertyChanging("nume");
                _nume = StructuralObject.SetValidValue(value, false, "nume");
                ReportPropertyChanged("nume");
                OnnumeChanged();
            }
        }
        private global::System.String _nume;
        partial void OnnumeChanging(global::System.String value);
        partial void OnnumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String parola
        {
            get
            {
                return _parola;
            }
            set
            {
                OnparolaChanging(value);
                ReportPropertyChanging("parola");
                _parola = StructuralObject.SetValidValue(value, false, "parola");
                ReportPropertyChanged("parola");
                OnparolaChanged();
            }
        }
        private global::System.String _parola;
        partial void OnparolaChanging(global::System.String value);
        partial void OnparolaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean tip_utilizator
        {
            get
            {
                return _tip_utilizator;
            }
            set
            {
                Ontip_utilizatorChanging(value);
                ReportPropertyChanging("tip_utilizator");
                _tip_utilizator = StructuralObject.SetValidValue(value, "tip_utilizator");
                ReportPropertyChanged("tip_utilizator");
                Ontip_utilizatorChanged();
            }
        }
        private global::System.Boolean _tip_utilizator;
        partial void Ontip_utilizatorChanging(global::System.Boolean value);
        partial void Ontip_utilizatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean active
        {
            get
            {
                return _active;
            }
            set
            {
                OnactiveChanging(value);
                ReportPropertyChanging("active");
                _active = StructuralObject.SetValidValue(value, "active");
                ReportPropertyChanged("active");
                OnactiveChanged();
            }
        }
        private global::System.Boolean _active;
        partial void OnactiveChanging(global::System.Boolean value);
        partial void OnactiveChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MagazinModel", "FK_Bon_Operator", "Bonuri")]
        public EntityCollection<Bonuri> Bonuris
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Bonuri>("MagazinModel.FK_Bon_Operator", "Bonuri");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Bonuri>("MagazinModel.FK_Bon_Operator", "Bonuri", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
