//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin.Models.EntytyLayer
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Stocuri
    {
        private readonly MagazinEntities context = new MagazinEntities();
        public int IDstoc { get; set; }
        public int produs { get; set; }
        public int cantitate { get; set; }
        public string um { get; set; }
        public System.DateTime aprovizionare { get; set; }
        public Nullable<System.DateTime> expirare { get; set; }
        public decimal pret_achizitie { get; set; }
        public decimal pret_vanzare { get; set; }
        public bool active { get; set; }

        public virtual Produse Produse { get; set; }

        public string ProdusName
        {
            get
            {
                var produs = context.spGetProdusById(this.produs).FirstOrDefault();
                return produs?.nume_prod ?? "Unknown Product";
            }
        }
    }
}
